# configuration for React-app
FROM node:alpine3.10

WORKDIR /DevOpsTestingapp as frontend

COPY ./package.json /DevOpsTestingapp

RUN npm install

COPY . .
RUN npm build

# configuaration for nginx

FROM nginx:alpine3.17

WORKDIR /usr/share/nginx/html

RUN -rm -rf ./*

COPY --from=frontend /DevOpsTestingapp/build .

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]

